/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts/$accountId'
import { Route as AccountsNewRouteImport } from './routes/accounts/new'
import { Route as AuditLogsIndexRouteImport } from './routes/audit-logs/index'
import { Route as AuditLogsAuditLogIdRouteImport } from './routes/audit-logs/$auditLogId'
import { Route as JournalsIndexRouteImport } from './routes/journals/index'
import { Route as JournalsJournalIdRouteImport } from './routes/journals/$journalId'
import { Route as JournalsNewRouteImport } from './routes/journals/new'
import { Route as TagsIndexRouteImport } from './routes/tags/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsIndexRoute = AuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsAuditLogIdRoute = AuditLogsAuditLogIdRouteImport.update({
  id: '/audit-logs/$auditLogId',
  path: '/audit-logs/$auditLogId',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsIndexRoute = JournalsIndexRouteImport.update({
  id: '/journals/',
  path: '/journals/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsJournalIdRoute = JournalsJournalIdRouteImport.update({
  id: '/journals/$journalId',
  path: '/journals/$journalId',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsNewRoute = JournalsNewRouteImport.update({
  id: '/journals/new',
  path: '/journals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/audit-logs/$auditLogId': typeof AuditLogsAuditLogIdRoute
  '/journals/$journalId': typeof JournalsJournalIdRoute
  '/journals/new': typeof JournalsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/audit-logs/': typeof AuditLogsIndexRoute
  '/journals/': typeof JournalsIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/audit-logs/$auditLogId': typeof AuditLogsAuditLogIdRoute
  '/journals/$journalId': typeof JournalsJournalIdRoute
  '/journals/new': typeof JournalsNewRoute
  '/accounts': typeof AccountsIndexRoute
  '/audit-logs': typeof AuditLogsIndexRoute
  '/journals': typeof JournalsIndexRoute
  '/tags': typeof TagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/audit-logs/$auditLogId': typeof AuditLogsAuditLogIdRoute
  '/journals/$journalId': typeof JournalsJournalIdRoute
  '/journals/new': typeof JournalsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/audit-logs/': typeof AuditLogsIndexRoute
  '/journals/': typeof JournalsIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/audit-logs/$auditLogId'
    | '/journals/$journalId'
    | '/journals/new'
    | '/accounts/'
    | '/audit-logs/'
    | '/journals/'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/audit-logs/$auditLogId'
    | '/journals/$journalId'
    | '/journals/new'
    | '/accounts'
    | '/audit-logs'
    | '/journals'
    | '/tags'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/audit-logs/$auditLogId'
    | '/journals/$journalId'
    | '/journals/new'
    | '/accounts/'
    | '/audit-logs/'
    | '/journals/'
    | '/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
  AccountsNewRoute: typeof AccountsNewRoute
  AuditLogsAuditLogIdRoute: typeof AuditLogsAuditLogIdRoute
  JournalsJournalIdRoute: typeof JournalsJournalIdRoute
  JournalsNewRoute: typeof JournalsNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  AuditLogsIndexRoute: typeof AuditLogsIndexRoute
  JournalsIndexRoute: typeof JournalsIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs/': {
      id: '/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs/$auditLogId': {
      id: '/audit-logs/$auditLogId'
      path: '/audit-logs/$auditLogId'
      fullPath: '/audit-logs/$auditLogId'
      preLoaderRoute: typeof AuditLogsAuditLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals/': {
      id: '/journals/'
      path: '/journals'
      fullPath: '/journals/'
      preLoaderRoute: typeof JournalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals/$journalId': {
      id: '/journals/$journalId'
      path: '/journals/$journalId'
      fullPath: '/journals/$journalId'
      preLoaderRoute: typeof JournalsJournalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals/new': {
      id: '/journals/new'
      path: '/journals/new'
      fullPath: '/journals/new'
      preLoaderRoute: typeof JournalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
  AccountsNewRoute: AccountsNewRoute,
  AuditLogsAuditLogIdRoute: AuditLogsAuditLogIdRoute,
  JournalsJournalIdRoute: JournalsJournalIdRoute,
  JournalsNewRoute: JournalsNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  AuditLogsIndexRoute: AuditLogsIndexRoute,
  JournalsIndexRoute: JournalsIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
