/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IconsRouteImport } from './routes/icons'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts/$accountId'
import { Route as AccountsNewRouteImport } from './routes/accounts/new'
import { Route as AllocationsIndexRouteImport } from './routes/allocations/index'
import { Route as AllocationsAllocationIdRouteImport } from './routes/allocations/$allocationId'
import { Route as AllocationsNewRouteImport } from './routes/allocations/new'
import { Route as AuditLogsIndexRouteImport } from './routes/audit-logs/index'
import { Route as AuditLogsAuditLogIdRouteImport } from './routes/audit-logs/$auditLogId'
import { Route as BudgetsIndexRouteImport } from './routes/budgets/index'
import { Route as BudgetsBudgetIdRouteImport } from './routes/budgets/$budgetId'
import { Route as BudgetsNewRouteImport } from './routes/budgets/new'
import { Route as JournalsIndexRouteImport } from './routes/journals/index'
import { Route as JournalsJournalIdRouteImport } from './routes/journals/$journalId'
import { Route as JournalsNewRouteImport } from './routes/journals/new'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates/$templateId'
import { Route as TemplatesNewRouteImport } from './routes/templates/new'
import { Route as TransactionsNewRouteImport } from './routes/transactions/new'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsRoute = IconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationsIndexRoute = AllocationsIndexRouteImport.update({
  id: '/allocations/',
  path: '/allocations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationsAllocationIdRoute = AllocationsAllocationIdRouteImport.update({
  id: '/allocations/$allocationId',
  path: '/allocations/$allocationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationsNewRoute = AllocationsNewRouteImport.update({
  id: '/allocations/new',
  path: '/allocations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsIndexRoute = AuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsAuditLogIdRoute = AuditLogsAuditLogIdRouteImport.update({
  id: '/audit-logs/$auditLogId',
  path: '/audit-logs/$auditLogId',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsIndexRoute = BudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsBudgetIdRoute = BudgetsBudgetIdRouteImport.update({
  id: '/budgets/$budgetId',
  path: '/budgets/$budgetId',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsNewRoute = BudgetsNewRouteImport.update({
  id: '/budgets/new',
  path: '/budgets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsIndexRoute = JournalsIndexRouteImport.update({
  id: '/journals/',
  path: '/journals/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsJournalIdRoute = JournalsJournalIdRouteImport.update({
  id: '/journals/$journalId',
  path: '/journals/$journalId',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsNewRoute = JournalsNewRouteImport.update({
  id: '/journals/new',
  path: '/journals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/icons': typeof IconsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/allocations/$allocationId': typeof AllocationsAllocationIdRoute
  '/allocations/new': typeof AllocationsNewRoute
  '/audit-logs/$auditLogId': typeof AuditLogsAuditLogIdRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdRoute
  '/budgets/new': typeof BudgetsNewRoute
  '/journals/$journalId': typeof JournalsJournalIdRoute
  '/journals/new': typeof JournalsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/allocations/': typeof AllocationsIndexRoute
  '/audit-logs/': typeof AuditLogsIndexRoute
  '/budgets/': typeof BudgetsIndexRoute
  '/journals/': typeof JournalsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/icons': typeof IconsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/allocations/$allocationId': typeof AllocationsAllocationIdRoute
  '/allocations/new': typeof AllocationsNewRoute
  '/audit-logs/$auditLogId': typeof AuditLogsAuditLogIdRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdRoute
  '/budgets/new': typeof BudgetsNewRoute
  '/journals/$journalId': typeof JournalsJournalIdRoute
  '/journals/new': typeof JournalsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts': typeof AccountsIndexRoute
  '/allocations': typeof AllocationsIndexRoute
  '/audit-logs': typeof AuditLogsIndexRoute
  '/budgets': typeof BudgetsIndexRoute
  '/journals': typeof JournalsIndexRoute
  '/tags': typeof TagsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/icons': typeof IconsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/allocations/$allocationId': typeof AllocationsAllocationIdRoute
  '/allocations/new': typeof AllocationsNewRoute
  '/audit-logs/$auditLogId': typeof AuditLogsAuditLogIdRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdRoute
  '/budgets/new': typeof BudgetsNewRoute
  '/journals/$journalId': typeof JournalsJournalIdRoute
  '/journals/new': typeof JournalsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/allocations/': typeof AllocationsIndexRoute
  '/audit-logs/': typeof AuditLogsIndexRoute
  '/budgets/': typeof BudgetsIndexRoute
  '/journals/': typeof JournalsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/icons'
    | '/login'
    | '/register'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/allocations/$allocationId'
    | '/allocations/new'
    | '/audit-logs/$auditLogId'
    | '/budgets/$budgetId'
    | '/budgets/new'
    | '/journals/$journalId'
    | '/journals/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/transactions/new'
    | '/accounts/'
    | '/allocations/'
    | '/audit-logs/'
    | '/budgets/'
    | '/journals/'
    | '/tags/'
    | '/templates/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/icons'
    | '/login'
    | '/register'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/allocations/$allocationId'
    | '/allocations/new'
    | '/audit-logs/$auditLogId'
    | '/budgets/$budgetId'
    | '/budgets/new'
    | '/journals/$journalId'
    | '/journals/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/transactions/new'
    | '/accounts'
    | '/allocations'
    | '/audit-logs'
    | '/budgets'
    | '/journals'
    | '/tags'
    | '/templates'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/icons'
    | '/login'
    | '/register'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/allocations/$allocationId'
    | '/allocations/new'
    | '/audit-logs/$auditLogId'
    | '/budgets/$budgetId'
    | '/budgets/new'
    | '/journals/$journalId'
    | '/journals/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/transactions/new'
    | '/accounts/'
    | '/allocations/'
    | '/audit-logs/'
    | '/budgets/'
    | '/journals/'
    | '/tags/'
    | '/templates/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  IconsRoute: typeof IconsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
  AccountsNewRoute: typeof AccountsNewRoute
  AllocationsAllocationIdRoute: typeof AllocationsAllocationIdRoute
  AllocationsNewRoute: typeof AllocationsNewRoute
  AuditLogsAuditLogIdRoute: typeof AuditLogsAuditLogIdRoute
  BudgetsBudgetIdRoute: typeof BudgetsBudgetIdRoute
  BudgetsNewRoute: typeof BudgetsNewRoute
  JournalsJournalIdRoute: typeof JournalsJournalIdRoute
  JournalsNewRoute: typeof JournalsNewRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  AllocationsIndexRoute: typeof AllocationsIndexRoute
  AuditLogsIndexRoute: typeof AuditLogsIndexRoute
  BudgetsIndexRoute: typeof BudgetsIndexRoute
  JournalsIndexRoute: typeof JournalsIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons': {
      id: '/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof IconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocations/': {
      id: '/allocations/'
      path: '/allocations'
      fullPath: '/allocations/'
      preLoaderRoute: typeof AllocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocations/$allocationId': {
      id: '/allocations/$allocationId'
      path: '/allocations/$allocationId'
      fullPath: '/allocations/$allocationId'
      preLoaderRoute: typeof AllocationsAllocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocations/new': {
      id: '/allocations/new'
      path: '/allocations/new'
      fullPath: '/allocations/new'
      preLoaderRoute: typeof AllocationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs/': {
      id: '/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs/$auditLogId': {
      id: '/audit-logs/$auditLogId'
      path: '/audit-logs/$auditLogId'
      fullPath: '/audit-logs/$auditLogId'
      preLoaderRoute: typeof AuditLogsAuditLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/': {
      id: '/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof BudgetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/$budgetId': {
      id: '/budgets/$budgetId'
      path: '/budgets/$budgetId'
      fullPath: '/budgets/$budgetId'
      preLoaderRoute: typeof BudgetsBudgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/new': {
      id: '/budgets/new'
      path: '/budgets/new'
      fullPath: '/budgets/new'
      preLoaderRoute: typeof BudgetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals/': {
      id: '/journals/'
      path: '/journals'
      fullPath: '/journals/'
      preLoaderRoute: typeof JournalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals/$journalId': {
      id: '/journals/$journalId'
      path: '/journals/$journalId'
      fullPath: '/journals/$journalId'
      preLoaderRoute: typeof JournalsJournalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals/new': {
      id: '/journals/new'
      path: '/journals/new'
      fullPath: '/journals/new'
      preLoaderRoute: typeof JournalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  IconsRoute: IconsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
  AccountsNewRoute: AccountsNewRoute,
  AllocationsAllocationIdRoute: AllocationsAllocationIdRoute,
  AllocationsNewRoute: AllocationsNewRoute,
  AuditLogsAuditLogIdRoute: AuditLogsAuditLogIdRoute,
  BudgetsBudgetIdRoute: BudgetsBudgetIdRoute,
  BudgetsNewRoute: BudgetsNewRoute,
  JournalsJournalIdRoute: JournalsJournalIdRoute,
  JournalsNewRoute: JournalsNewRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TemplatesNewRoute: TemplatesNewRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  AllocationsIndexRoute: AllocationsIndexRoute,
  AuditLogsIndexRoute: AuditLogsIndexRoute,
  BudgetsIndexRoute: BudgetsIndexRoute,
  JournalsIndexRoute: JournalsIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
